# Generated by Django 4.0 on 2022-03-06 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=7, default=0.0, max_digits=12)),
                ('status', models.CharField(choices=[['Pending', 'Pending'], ['Invalid', 'Invalid'], ['Authorized', 'Authorized']], default='invalid', max_length=200)),
                ('verified', models.BooleanField(default=False)),
                ('sender', models.CharField(help_text='The user hash:id who sends the coins', max_length=200, unique=True)),
                ('receiver', models.CharField(help_text='The wallet receive address who receive the funds', max_length=200, unique=True)),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
