# Generated by Django 4.0 on 2022-03-11 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_alter_transaction_receiver_alter_transaction_sender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='verified',
            new_name='completed',
        ),
        migrations.AddField(
            model_name='transaction',
            name='txType',
            field=models.CharField(default=False, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[['Pending', 'Pending'], ['Invalid', 'Invalid'], ['Authorized', 'Authorized']], default='Invalid', max_length=200),
        ),
    ]
